# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master


jobs:
  - job : Test
    timeoutInMinutes: 120
    strategy:
      matrix:
        linux:
          imageName: 'linux_vm_vahila'
        mac:
          imageName: 'vahila_mac_bgl'
        windows:
          imagename: 'win_iat'
    pool:
      name: Default
      demands:
        - agent.name -equals $(imageName)
    steps:
      - script: mw -using bci mvn clean integration-test
